### ISSUE TITLE
TypeError: __init__() got an unexpected keyword argument 'capture_output'

### ISSUE THREAD

**Issue by cwsecur1ty** [cwsecur1ty/Debian-Hardener-Toolkit#1]
[NOTICE] Don't forget to make sure the audit scripts are executable. ('chmod +x audits/*.sh')
[*] Running system audits.

[*] Running audits/audit_permissions.sh.
Traceback (most recent call last):
  File "main.py", line 81, in <module>
    main()
  File "main.py", line 68, in main
    audit_results = audit_system()
  File "main.py", line 23, in audit_system
    stdout, stderr = run_script(script) # executes a given Bash script and captures its output
  File "main.py", line 6, in run_script
    result = subprocess.run(['bash', script_path], capture_output=True, text=True)
  File "/usr/lib/python3.6/subprocess.py", line 423, in run
    with Popen(*popenargs, **kwargs) as process:
TypeError: __init__() got an unexpected keyword argument 'capture_output'

**Comment by cwsecur1ty** [comment]
The capture_output parameter is not available in the subprocess.run() function in Python 3.6. This parameter was introduced in Python 3.7.

I need to capture the output using stdout and stderr parameters instead. I have updated main.py to reflect the changes.
