### ISSUE TITLE
TypeError: __init__() got an unexpected keyword argument 'text'

### ISSUE THREAD

**Issue by cwsecur1ty** [cwsecur1ty/Debian-Hardener-Toolkit#2]
[NOTICE] Don't forget to make sure the audit scripts are executable. ('chmod +x audits/*.sh')
[*] Running system audits.

[*] Running audits/audit_permissions.sh.
Traceback (most recent call last):
  File "main.py", line 86, in <module>
    main()
  File "main.py", line 73, in main
    audit_results = audit_system()
  File "main.py", line 26, in audit_system
    stdout, stderr = run_script(script) # executes a given Bash script and captures its output
  File "main.py", line 7, in run_script
    result = subprocess.run(['bash', script_path], stdout=subprocess.PIPE, stderr=subprocess.PIPE, text=True)
  File "/usr/lib/python3.6/subprocess.py", line 423, in run
    with Popen(*popenargs, **kwargs) as process:
TypeError: __init__() got an unexpected keyword argument 'text'

**Comment by cwsecur1ty** [comment]
Updated: run_script(script_path) function.
Action: Uploaded amended main.py.

The text parameter in subprocess.run() was introduced in Python 3.7. For Python 3.6, I need to use the universal_newlines parameter instead, which has the same effect.
